variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "false"

stages:
   - push2github

push2github:
  stage: push2github
  tags:
    - dind
  script:
    - git clone --mirror $CI_REPOSITORY_URL
    - cd puppet-sc_firewall.git
    - git remote set-url --push origin https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_firewall.git
    - git push --quiet --mirror
